# Generated by Django 3.1.7 on 2021-03-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='label',
            new_name='RecordLabel',
        ),
        migrations.AlterField(
            model_name='artist',
            name='artistName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='artist',
            name='firstName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='artist',
            name='lastName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='label',
            name='founder',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='label',
            name='labelID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='label',
            name='labelName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='label',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
