# Generated by Django 3.1.7 on 2021-03-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artistName',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
